### ISSUE TITLE
Add keyboard handler for playing/pausing/skipping YT video

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/music-menubar#13]
space should pause, maybe arrow keys skip? Would also be cool to have touchbar support for macOS

**Comment by Tails128** [comment]
I would like to work on this, I worked on something like this already.

As for the touchbar support for macOS it may require some time since I never worked on it, but it'd be nice to work on it as well!

**Comment by aaronleopold** [comment]
@Tails128 Awesome, sounds good! If it could be some sort of reusable React hook that would be perfect. Be sure to create the file in the util folder, something like `src/renderer/util/useKeyboard.ts`. The touchbar support is really just a bonus

**Comment by Tails128** [comment]
@aaronleopold I should be over, I was about to test but could I ask you for some explanation about the `ELECTRON_WEBPACK_APP_STORAGE_KEY=` value in `.env` file? 

Which storage key are you referring to? Without it, the build just closes the window before I can see anything

**Comment by aaronleopold** [comment]
@Tails128 are you getting any errors in the developer console or the terminal along with the webpack output? I can try and help more if I see any specific errors you may be encountering. 

For the `ELECTRON_WEBPACK_APP_STORAGE_KEY` you can set it to any arbitrary string. *technically* you should be able to not set it to anything and it will still work (although this will change) based on how I have it configured. What this does is provide mobx a key for accessing the store that all the user data (playlists, api keys, etc). I have it as an env variable so that I can create a very secure key that would be packaged into a release.  To see where I use the variable, check out `packages/electron/src/renderer/models/index.tsx`

Also, be sure to keep the port at 8080.

**Comment by Tails128** [comment]
@aaronleopold it could be nice to add it to the .env.example file for future readings!
Turns out the crashing was on my side, fixed it so don't worry about it!
As for the touchbar support I believe I will go in a separate PR to keep it more ordinate.

I have just tested and I am submitting the keyboard PR right now! ^^

**Comment by aaronleopold** [comment]
@Tails128 I don't think adding something like that to the example would hurt :) I'll go ahead and do that! 

And I'll be able to review the PR either later tonight or tomorrow (but I won't keep you waiting too long 😄)

**Comment by aaronleopold** [comment]
Thanks @Tails128!! I went ahead and merged the PR and I'll mark it as valid. I'll be keeping this issue open (and renaming it) to reflect the touchbar support (I probably should have separated these out anyways)
