### ISSUE TITLE
Create youtube link parser

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/music-menubar#6]
Something essentially like the following function with the signature:

```tsx
// Example:
// url = https://www.youtube.com/watch?v=rCFmLjGq3Jg&list=RDrCFmLjGq3Jg&start_radio=1&t=20
// params = { v: rCFmLjGq3Jg, list: RDrCFmLjGq3Jg, start_radio: 1, t=20 }
function parseYouTubeUrl(url: string) {
   /* ... code ... */
   return params
}
```

This way, the addition of a video or playlist may be altered to allow a user to simply paste the entire link. Be sure this is in the `src/renderer/utils/index.ts` file

**Comment by SteveAndreou** [comment]
Hi Aaron,

Cool project, I'm participating in Hacktoberfest for the first time and I can help complete this issue for you.

We can just create a little URL parsing utility by using an already included node module.

I haven't contributed to any other projects on GitHub before, do I need to be assigned this ticket before I can create a pull request?

`
import { parse } from "querystring";

// Issue: https://github.com/aaronleopold/music-menubar/issues/6
// Example:
// url = https://www.youtube.com/watch?v=rCFmLjGq3Jg&list=RDrCFmLjGq3Jg&start_radio=1&t=20
// params = { v: rCFmLjGq3Jg, list: RDrCFmLjGq3Jg, start_radio: 1, t=20 }

export const parseUrl = (url: string) => {
    //No string provided
    if (url === "" || url === undefined) return null;

    //No query string detected
    if (!url.includes("?")) return null;

    const queryString = url.split("?")[1];
    const params = parse(queryString);

    return params;
};

`

**Comment by aaronleopold** [comment]
If you're talking about querystring that should work perfectly. I'll go ahead and assign you but I don't believe any PRs count towards the event yet so keep that in mind
